import { Button } from "@/components/ui/button"
import {
  Dialog,
  DialogClose,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from "@/components/ui/dialog"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { X } from "lucide-react"
import { ReactNode, useState } from "react"

export function AddStudentDialog({children} : {children : ReactNode}) {
  const [formData, setFormData] = useState({
    fullName: "",
    dob: "",
    gender: "",
    guardianAddress: "",
    class: "",
    guardianContact: "",
    studentId: "S-101",
  });

  const handleInputChange = (e: React.ChangeEvent<HTMLInputElement | HTMLSelectElement>) => {
    const { name, value } = e.target;
    setFormData((prev) => ({
      ...prev,
      [name]: value,
    }));
  };

  const handleSubmit = (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    console.log("Form Data:", formData);
    // Add your submission logic here (API call, etc.)
  };

const studentFormFields = [
  {
    name: "fullName",
    label: "Full Name",
    type: "text",
    placeholder: "Enter full name",
    required: true,
  },
  {
    name: "dob",
    label: "Date of Birth",
    type: "date",
    placeholder: "mm/dd/yyyy",
    required: true,
  },
  {
    name: "gender",
    label: "Gender",
    type: "select",
    options: [
      { value: "male", label: "Male" },
      { value: "female", label: "Female" },
    ],
    placeholder: "Select gender",
    required: true,
  },
  {
    name: "guardianAddress",
    label: "Parent/Guardian Address",
    type: "text",
    placeholder: "Enter address",
    required: true,
  },
  {
    name: "class",
    label: "Class",
    type: "text", // or 'select' if you have specific classes
    placeholder: "Enter class",
    required: true,
  },
  {
    name: "guardianContact",
    label: "Parent/Guardian Contact",
    type: "tel",
    placeholder: "Enter phone number",
    required: true,
  },
  {
    name: "studentId",
    label: "Student ID (Autogenerated)",
    type: "text",
    placeholder: "S-101",
    disabled: true, // Since you mentioned it's autogenerated
    defaultValue: "S-101", // Example default value
  },
];

  return (
    <Dialog>
        <DialogTrigger asChild>
          {/* <Button variant="outline">Open Dialog</Button> */}
          {children}
        </DialogTrigger>
        <DialogContent className="sm:max-w-[425px]">
      <form onSubmit={handleSubmit}>
          <DialogHeader>
                <p>Add New Student</p>
            <DialogDescription>
                Fill in the details to add a new student
            </DialogDescription>
          </DialogHeader>
          {/* <div className="grid gap-4 grid-cols-2">
            <div className="grid gap-3">
              <Label htmlFor="name-1">Name</Label>
              <Input id="name-1" name="name" defaultValue="Pedro Duarte" />
            </div>
            <div className="grid gap-3">
              <Label htmlFor="username-1">Username</Label>
              <Input id="username-1" name="username" defaultValue="@peduarte" />
            </div>
          </div> */}
    
            <div className="grid grid-cols-2 my-[25px] gap-x-[20px]">
    {studentFormFields.map((field) => (
    <div key={field.name} className={`flex flex-col gap-2 my-2 ${field.name == "studentId"? "col-span-2":null } `}>
      <label htmlFor={field.name} className="font-medium text-gray-700 text-[14px]">
        {field.label}
      </label>

      {field.type === "select" ? (
        <select
          name={field.name}
          id={field.name}
          className="border p-2 rounded-[6px]"
          required={field.required}
          value={formData[field.name as keyof typeof formData]}
          onChange={handleInputChange}
        >
          <option value="">{field.placeholder}</option>
          {field.options?.map((opt) => (
            <option key={opt.value} value={opt.value}>
              {opt.label}
            </option>
          ))}
        </select>
      ) : (
        <input
          type={field.type}
          name={field.name}
          id={field.name}
          placeholder={field.placeholder}
          disabled={field.disabled}
          value={formData[field.name as keyof typeof formData]}
          onChange={handleInputChange}
          className={`border p-2 rounded-[6px] ${
            field.disabled ? "bg-gray-100 text-gray-500 cursor-not-allowed" : ""
          }`}
          required={field.required}
        
        />
      )}
    </div>
  ))}
 </div>
          <DialogFooter>
            <Button type="submit" style={{backgroundColor: '#9747FF'}} className="text-white">Add Student</Button>
          </DialogFooter>
      </form>
        </DialogContent>
    </Dialog>
  )
}

export function AddTeacherDialog({children} : {children : ReactNode}) {
  const [formData, setFormData] = useState({
    fullName: "",
    dob: "",
    gender: "",
    email: "",
    subject: "",
    contact: "",
    teacherId: "T-101",
  });

  const handleInputChange = (e: React.ChangeEvent<HTMLInputElement | HTMLSelectElement>) => {
    const { name, value } = e.target;
    setFormData((prev) => ({
      ...prev,
      [name]: value,
    }));
  };

  const handleSubmit = (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    console.log("Form Data:", formData);
    // fetch will be added here
  };

const teacherFormFields = [
  {
    name: "fullName",
    label: "Full Name",
    type: "text",
    placeholder: "Enter full name",
    required: true,
  },
  {
    name: "dob",
    label: "Date of Birth",
    type: "date",
    placeholder: "mm/dd/yyyy",
    required: true,
  },
  {
    name: "gender",
    label: "Gender",
    type: "select",
    options: [
      { value: "male", label: "Male" },
      { value: "female", label: "Female" },
    ],
    placeholder: "Select gender",
    required: true,
  },
  {
    name: "email",
    label: "Email",
    type: "email",
    placeholder: "Enter email address",
    required: true,
  },
  {
    name: "subject",
    label: "Subject",
    type: "text",
    placeholder: "Enter subject",
    required: true,
  },
  {
    name: "contact",
    label: "Contact Number",
    type: "tel",
    placeholder: "Enter phone number",
    required: true,
  },
  {
    name: "teacherId",
    label: "Teacher ID (Autogenerated)",
    type: "text",
    placeholder: "T-101",
    disabled: true,
    defaultValue: "T-101",
  },
];

  return (
    <Dialog>
        <DialogTrigger asChild>
          {children}
        </DialogTrigger>
        <DialogContent className="sm:max-w-[425px]">
      <form onSubmit={handleSubmit}>
          <DialogHeader>
                <p>Add New Teacher</p>
            <DialogDescription>
                Fill in the details to add a new teacher
            </DialogDescription>
          </DialogHeader>
    
            <div className="grid grid-cols-2 my-[25px] gap-x-[20px]">
    {teacherFormFields.map((field) => (
    <div key={field.name} className={`flex flex-col gap-2 my-2 ${field.name == "teacherId"? "col-span-2":null } `}>
      <label htmlFor={field.name} className="font-medium text-gray-700 text-[14px]">
        {field.label}
      </label>

      {field.type === "select" ? (
        <select
          name={field.name}
          id={field.name}
          className="border p-2 rounded-[6px]"
          required={field.required}
          value={formData[field.name as keyof typeof formData]}
          onChange={handleInputChange}
        >
          <option value="">{field.placeholder}</option>
          {field.options?.map((opt) => (
            <option key={opt.value} value={opt.value}>
              {opt.label}
            </option>
          ))}
        </select>
      ) : (
        <input
          type={field.type}
          name={field.name}
          id={field.name}
          placeholder={field.placeholder}
          disabled={field.disabled}
          value={formData[field.name as keyof typeof formData]}
          onChange={handleInputChange}
          className={`border p-2 rounded-[6px] ${
            field.disabled ? "bg-gray-100 text-gray-500 cursor-not-allowed" : ""
          }`}
          required={field.required}
        
        />
      )}
    </div>
  ))}
 </div>
          <DialogFooter>
            <Button type="submit" style={{backgroundColor: '#9747FF'}} className="text-white">Add Teacher</Button>
          </DialogFooter>
      </form>
        </DialogContent>
    </Dialog>
  )
}

type props = {
    fullName: string,
    dob: string,
    gender: "male" | "female",
    guardianAddress: string,
    class: string,
    guardianContact: string,
    studentId: string,
}



export function StudentDialog({children,props} : {children : ReactNode,props:any}) {
  const [formData, setFormData] = useState(props as object);
    console.log(props)
  const handleInputChange = (e: React.ChangeEvent<HTMLInputElement | HTMLSelectElement>) => {
    const { name, value } = e.target;
    setFormData((prev) => ({
      ...prev,
      [name]: value,
    }));
  };

  const handleSubmit = (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    console.log("Form Data:", formData);
    // submission will be added here
  };

  const handleDelete = () => {
    console.log("Deleting student:", formData);
    // delete will be added here
  };

const studentFormFields = [
  {
    name: "fullName",
    label: "Full Name",
    type: "text",
    placeholder: "Enter full name",
    required: true,
  },
  {
    name: "dob",
    label: "Date of Birth",
    type: "date",
    placeholder: "mm/dd/yyyy",
    required: true,
  },
  {
    name: "gender",
    label: "Gender",
    type: "select",
    options: [
      { value: "male", label: "Male" },
      { value: "female", label: "Female" },
    ],
    placeholder: "Select gender",
    required: true,
  },
  {
    name: "guardianAddress",
    label: "Parent/Guardian Address",
    type: "text",
    placeholder: "Enter address",
    required: true,
  },
  {
    name: "class",
    label: "Class",
    type: "text",
    placeholder: "Enter class",
    required: true,
  },
  {
    name: "guardianContact",
    label: "Parent/Guardian Contact",
    type: "tel",
    placeholder: "Enter phone number",
    required: true,
  },
  {
    name: "studentId",
    label: "Student ID (Autogenerated)",
    type: "text",
    placeholder: "S-101",
    disabled: true,
    defaultValue: "S-101",
  },
];

  return (
    <Dialog>
        <DialogTrigger asChild>
          {/* <Button variant="outline">Open Dialog</Button> */}
          {children}
        </DialogTrigger>
        <DialogContent className="sm:max-w-[425px]">
      <form onSubmit={handleSubmit}>
          <DialogHeader>
                <p>Add New Student</p>
            <DialogDescription>
                Fill in the details to add a new student
            </DialogDescription>
          </DialogHeader>
          {/* <div className="grid gap-4 grid-cols-2">
            <div className="grid gap-3">
              <Label htmlFor="name-1">Name</Label>
              <Input id="name-1" name="name" defaultValue="Pedro Duarte" />
            </div>
            <div className="grid gap-3">
              <Label htmlFor="username-1">Username</Label>
              <Input id="username-1" name="username" defaultValue="@peduarte" />
            </div>
          </div> */}
    
            <div className="grid grid-cols-2 my-[25px] gap-x-[20px]">
    {studentFormFields.map((field) => (
    <div key={field.name} className={`flex flex-col gap-2 my-2 ${field.name == "studentId"? "col-span-2":null } `}>
      <label htmlFor={field.name} className="font-medium text-gray-700 text-[14px]">
        {field.label}
      </label>

      {field.type === "select" ? (
        <select
          name={field.name}
          id={field.name}
          className="border p-2 rounded-[6px]"
          required={field.required}
          value={formData[field.name as keyof typeof formData]}
          onChange={handleInputChange}
        >
          <option value="">{field.placeholder}</option>
          {field.options?.map((opt) => (
            <option key={opt.value} value={opt.value}>
              {opt.label}
            </option>
          ))}
        </select>
      ) : (
        <input
          type={field.type}
          name={field.name}
          id={field.name}
          placeholder={field.placeholder}
          disabled={field.disabled}
          value={formData[field.name as keyof typeof formData]}
          onChange={handleInputChange}
          className={`border p-2 rounded-[6px] ${
            field.disabled ? "bg-gray-100 text-gray-500 cursor-not-allowed" : ""
          }`}
          required={field.required}
        
        />
      )}
    </div>
  ))}
 </div>
          <DialogFooter className="flex flex-row-reverse items-center justify-between">
            <Button type="submit" style={{backgroundColor: '#9747FF'}} className="text-white w-[40%]">Save Data</Button>
            <Button type="button" onClick={handleDelete} className="bg-red-500 w-[40%]">Delete Student</Button>
          </DialogFooter>
      </form>
        </DialogContent>
    </Dialog>
  )
}
