import { useState } from "react"
import { FaEye, FaEyeSlash } from 'react-icons/fa';
import { Dialog, DialogClose, DialogContent, DialogFooter } from "../ui/dialog";
import { DialogDescription } from "@radix-ui/react-dialog";
import Link from "next/link";
import { CheckCircle } from "lucide-react";
import { ToastContainer,toast } from "react-toastify";
import { Spinner } from "../ui/spinner";
interface formData {
    schoolName: string
    subdomain: string
    adminEmail: string
    password: string
    phoneNumber: string
    schoolAddress: string
    agreement: boolean
}
export function PageOne({data,changeData,step,setStep}: any){
    const checkName = (email:string) => {
        const regex = /^[a-zA-Z ]+$/
        if(regex.test(email)){
            return true
        }else{
            return false
        }
    }
    const [nameAuth,setNameAuth] = useState(() => checkName(data["schoolName"]))
    const checkField = (e : React.ChangeEvent<HTMLInputElement>,name:string) => {
            const regex = /^[a-zA-Z ]+$/;
            regex.test(data.schoolName) ? setNameAuth(true) : setNameAuth(false)
    }
    const forms = [
        {
            label:"School Name",
            name:"schoolName",
            type:"text",
            subtext:"Enter your school name "
        }
    ]

    return <div className="my-[25px] border-[1px] border-[#641BC4] rounded-[6px] w-[95%] sm:w-[45%] flex flex-col items-center justify-between py-[40px] h-[445px]">
        <div className="flex flex-col items-center">
        <p className="text-[20px] font-bold">Register Your School</p>
        <p>Let's get your school set up on ParaLearn RMS</p>
        </div>
        <div className="w-[90%] space-y-3">
            {forms.map((form,index) => (
            <div key={index} className="flex flex-col w-[100%] p-[10px]">
                <label htmlFor={form.name}>{form.label}</label>
                <input type="text" name={form.name} value={data[form.name]} onChange={(e) => {changeData(e); checkField(e,form.name)}} className="border-[1px] border-[#641BC4] focus:border-[2px] focus:outline-none h-[45px] w-[100%] p-[13px]" readOnly={form.name == "subdomain"}/> 
                {form.name == "schoolName" && !nameAuth && <p className="text-red-600" >School name should contain only alphabets</p>}
            </div>
        ))}
            <div className="flex flex-col w-[100%] p-[10px]">
                <label htmlFor="subdomain">Subdomain (Autogenerated)</label>
                <div className="flex flex-row items-center">
                <input type="text" name="subdomain" value={data["subdomain"]} onChange={(e) => {changeData(e)}} className="border-[1px] border-gray-300 focus:border-[2px] focus:outline-none h-[45px] w-[90%] p-[13px]" readOnly/> 
                <div className="w-[15%] text-center border-gray-300 border-[1px] h-[45px] flex items-center justify-center">
                    <p className="text-center">.pln.ng</p>
                </div>
                </div>
            </div>
        </div>
            {step == 1 &&   <button disabled={!nameAuth} style={!nameAuth? {backgroundColor:"#a166f0"} : {backgroundColor:"#641BC4"}} onClick={() => {setStep(step + 1)}} className="w-[85%] rounded-[12px] bg-[#a166f0] font-semibold text-white h-[52px] flex flex-row items-center justify-center ">
            continue </button>}
    </div>
}

export function PageTwo({data,changeData,step,setStep}: any){
    const emailCheck = () => {
         const emailRegex = /^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$/;
        if(data["adminEmail"].length > 0 && emailRegex.test(data["adminEmail"])){
            return true
        }else{return false}
    }
    const passwordCheck = () => {
        if(data["password"].length){
            return true
        }else{return false}
    }
    const [emailAuth, setemailAuth] = useState(emailCheck())
    const [showPassword, setshowPassword] = useState(false)
    const [passwordAuth, setPasswordAuth] = useState(passwordCheck())
    const forms = [
        {
            label:"Admin Email",
            name:"adminEmail",
            type:"text",
            subtext:"This will be your login email and school contact"
        }
    ]

   const checkEmail = (e : React.ChangeEvent<HTMLInputElement>) => {
  const emailRegex = /^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$/;
  if(emailRegex.test(e.target.value)){
    setemailAuth(true)
  }else{setemailAuth(false)}
}

    const checkPassword = (password : string) => {
        if(password.length >= 8 && password.length != 0){
            setPasswordAuth(true)
        } else{
            setPasswordAuth(false)
        }
    }


    return <div className="my-[25px] border-[1px] border-[#641BC4] rounded-[6px] w-[95%] md:w-[70%] lg:w-[45%] flex flex-col items-center justify-between py-[40px] min-h-[445px] h-auto">
        <div className="flex flex-col items-center">
        <p className="text-[20px] font-bold">Admin Account Setup</p>
        <p>Create your administrator account</p>
        </div>
        <div className="w-[90%] space-y-3">
            {forms.map((form,index) => (
            <div key={index} className="flex flex-col w-[100%] ">
                <label htmlFor={form.name}>{form.label}</label>
                <input type={form["type"]} name={form.name} value={data[form.name]} onChange={(e) => {changeData(e); checkEmail(e)}} className="border-[1px] border-[#641BC4] focus:border-[2px] focus:outline-none h-[45px] w-[100%] p-[13px]"/>
                {data[form.name] == "" && <p className="text-[12px]">{form.subtext}</p>}
                {!emailAuth && data[form.name] != "" && <p className="text-red-400">please enter a correct mail</p>}
            </div>
        ))}
        <div className="flex flex-col w-[100%] ">
                <label htmlFor="password">Password</label>
                <div className="relative">
                <input type={showPassword?"text":"password"} name="password" value={data["password"]} onChange={(e) => {changeData(e); checkPassword(e.target.value)}} className="border-[1px] border-[#641BC4] focus:border-[2px] focus:outline-none h-[45px] w-[100%] p-[13px]"/>
                <button onClick={() => setshowPassword(!showPassword)} className="absolute top-[30%] right-[15px]">{!showPassword? <FaEyeSlash/> : <FaEye/>}</button>
                </div>
                {data["password"] == "" && <p className="text-[12px]">Create a strong password</p>}
                {!passwordAuth && <p className="text-red-500 text-[12px]">password length must be more than 8</p>}
            </div>
        </div>
            {step == 2 &&   <div className="w-[100%] flex justify-evenly">
                   <button onClick={() => {setStep(step - 1)}} className="w-[35%] rounded-[12px]  font-semibold text-black h-[52px] flex flex-row items-center justify-center border-[1px] border-black">
            back </button>
                <button onClick={() => {setStep(step + 1)}} disabled={!emailAuth || !passwordAuth} style={!emailAuth || !passwordAuth? {backgroundColor:"#a166f0"} : {backgroundColor:"#641BC4"}} className="w-[35%] rounded-[12px] bg-[#641BC4] font-semibold text-white h-[52px] flex flex-row items-center justify-center">
            continue </button>
                </div>}
    </div>
}




export function PageThree({data,changeData,step,setStep}: any){

    const checkPhone = (phone:string) => {
        if(phone.length > 0){
            return true
        }else{
            return false
        }
    }

    const [disable,setDisable] = useState(false)
    const [isLoading, setIsLoading] = useState(false)
    const [phoneAuth, setPhoneAuth]  = useState(checkPhone(data["phoneNumber"]))
    const [agreement,setAgreement] = useState(data["agreement"])

    const submit =  async () => {
        setIsLoading(true)
        
        const backendData = {
            schoolName: data.schoolName,
            domain: data.subdomain,
            adminEmail: data.adminEmail,
            adminPassword: data.password,
            adminFirstName: "",
            adminLastName:"",
            phoneNumber: data.phoneNumber,
            schoolAddress: data.schoolAddress,
            motto: null,
            website: null,
        }

        try {
             const registerAdmin = await fetch('/api/proxy/auth/register-school',{
                headers:{
                    'Content-Type':'application/json'
                },
                method:'POST',
                body: JSON.stringify(backendData),
            })

            const res = await registerAdmin.json()
            if(!registerAdmin.ok) throw new Error(res.message || "Failed to create account. Please try again.")

             console.log(res);
                setDisable(true)
        } catch (error) {
            console.log(error);
            toast.error(error instanceof Error ? error.message : "An unexpected error occurred.");
        } finally {
            setIsLoading(false)
        }
    }

    const forms = [
   {
            label:"Phone Number",
            name:"phoneNumber",
            type:"number",
            subtext:"Enter your phone number"
        },
        {
            label:"School Address",
            name:"schoolAddress",
            type:"text",
            subtext:"Enter your school Address"
        }
    ]

    return <div className="my-[25px] border-[1px] border-[#641BC4] rounded-[6px] w-[95%] md:w-[70%] lg:w-[45%] flex flex-col items-center justify-between py-[40px] min-h-[445px] h-auto">
        <div className="flex flex-col items-center">
        <p className="text-[20px] font-bold">Contact Information</p>
        <p>Help us complete your school profile</p>
        </div>
        <div className="w-[90%] space-y-3">
            {forms.map((form) => (
            <div className="flex flex-col w-[100%] ">
                <label htmlFor={form.name}>{form.label}</label>
                <input type={form.type} name={form.name} value={data[form.name]} onChange={(e) => {changeData(e);checkPhone(e.target.value);setPhoneAuth(checkPhone(data["phoneNumber"]))}} className="border-[1px] border-[#641BC4] focus:border-[2px] focus:outline-none h-[45px] w-[100%] p-[13px]"/>
                <p className="text-[12px]">{form.subtext}</p>
            </div>
        ))}
        <div className=" w-[100%] mb-2 ">
            <input type="checkbox" name="agreement" checked={data.agreement} onChange={(e) => {changeData(e);setAgreement(e.target.checked)}} className="mr-2"/>
                <label htmlFor="agreement">I agree to the ParaLearn RMS Terms of Service and Privacy Policy. I confirm that I have the authority to register this school.</label>
            </div>
        {/* submit button */}
        <ToastContainer />
        </div>
            {step == 3 &&   <div className="w-[100%] flex justify-evenly">
                   <button onClick={() => {setStep(step - 1)}} disabled={isLoading} className="w-[35%] rounded-[12px]  font-semibold text-black h-[52px] flex flex-row items-center justify-center border-[1px] border-black">
            back </button>
            {/* create school */}
                <button onClick={submit} disabled={!phoneAuth || !agreement || isLoading} style={(!phoneAuth || !agreement || isLoading)? {backgroundColor:"#a166f0"} : {backgroundColor:"#641BC4"}} className="w-[35%] rounded-[12px] bg-[#641BC4] font-semibold text-white h-[52px] flex flex-row items-center justify-center gap-2">
                    {isLoading && <Spinner />}
                    {isLoading ? "Creating..." : "Create School"}
                </button>
                </div>}

            <Dialog open={disable} onOpenChange={() => setDisable(false)}>
                <DialogContent className="py-[35px]">
                    <DialogDescription className="flex flex-col items-center justify-evenly">
                        <CheckCircle className="size-32 text-[#3AC13A] p-3"/>
                        <p className="text-[20px]">Account Created, you can now login</p>
                    </DialogDescription>
                    <DialogFooter>
                        <Link href={"/auth/signin"} className="text-white font-bold w-[100%] ">
                            <button className="flex flex-row items-center justify-evenly w-[100%] h-[45px] rounded-[6px] bg-[#641BC4] my-4 text-white font-bold">Login</button>
                        </Link>
                    </DialogFooter>
                </DialogContent>
            </Dialog>
    </div>
}