interface formData {
        schoolName:"",
        subdomain:"",
        adminEmail:"",
        password:"",
        phoneNumber:"",
        schoolAddress:"",
        agreement:false
}
export function PageOne({data,changeData,step,setStep}: any){
    const forms = [
        {
            label:"School Name",
            name:"schoolName",
            type:"text",
            subtext:"Enter your school name "
        },
        {
            label:"Subdomain (Autogenerated)",
            name:"subdomain",
            type:"text",
            subtext:"Your school will be accessible at: .pl.ng"
        }
    ]

    return <div className="my-[25px] border-[1px] border-[#641BC4] rounded-[6px] w-[45%] flex flex-col items-center justify-between py-[40px] h-[445px]">
        <div className="flex flex-col items-center">
        <p className="text-[20px] font-bold">Register Your School</p>
        <p>Let's get your school set up on ParaLearn RMS</p>
        </div>
        <div className="w-[90%] space-y-3">
            {forms.map((form) => (
            <div className="flex flex-col w-[100%] ">
                <label htmlFor={form.name}>{form.label}</label>
                <input type="text" name={form.name} value={data.schoolName} onChange={(e) => changeData(e)} className="border-[1px] border-[#641BC4] h-[45px] w-[100%]"/>
                <p className="text-[12px]">{form.subtext}</p>
            </div>
        ))}
        </div>
            {step == 1 &&   <button onClick={() => {setStep(step + 1)}} className="w-[85%] rounded-[12px] bg-[#641BC4] font-semibold text-white h-[52px] flex flex-row items-center justify-center">
            continue </button>}
    </div>
}

export function PageTwo({data,changeData,step,setStep}: any){
    const forms = [
        {
            label:"Admin Email",
            name:"adminEmail",
            type:"text",
            subtext:"This will be your login email and school contact"
        },
        {
            label:"Password",
            name:"password",
            type:"password",
            subtext:"Create a strong password"
        }
    ]

    return <div className="my-[25px] border-[1px] border-[#641BC4] rounded-[6px] w-[45%] flex flex-col items-center justify-between py-[40px] h-[445px]">
        <div className="flex flex-col items-center">
        <p className="text-[20px] font-bold">Admin Account Setup</p>
        <p>Create your administrator account</p>
        </div>
        <div className="w-[90%] space-y-3">
            {forms.map((form) => (
            <div className="flex flex-col w-[100%] ">
                <label htmlFor={form.name}>{form.label}</label>
                <input type="text" name={form.name} value={data.schoolName} onChange={(e) => changeData(e)} className="border-[1px] border-[#641BC4] h-[45px] w-[100%]"/>
                <p className="text-[12px]">{form.subtext}</p>
            </div>
        ))}
        </div>
            {step == 2 &&   <div className="w-[100%] flex justify-evenly">
                   <button onClick={() => {setStep(step - 1)}} className="w-[35%] rounded-[12px]  font-semibold text-black h-[52px] flex flex-row items-center justify-center border-[1px] border-black">
            back </button>
                <button onClick={() => {setStep(step + 1)}} className="w-[35%] rounded-[12px] bg-[#641BC4] font-semibold text-white h-[52px] flex flex-row items-center justify-center">
            continue </button>
                </div>}
    </div>
}



export function PageThree({data,changeData,step,setStep}: any){
    const forms = [
   {
            label:"Phone Number",
            name:"phoneNumber",
            type:"number",
            subtext:"Enter your phone number"
        },
        {
            label:"School Address",
            name:"schoolAddress",
            type:"text",
            subtext:"Enter your school Address"
        }
    ]

    return <div className="my-[25px] border-[1px] border-[#641BC4] rounded-[6px] w-[45%] flex flex-col items-center justify-between py-[40px] h-[445px]">
        <div className="flex flex-col items-center">
        <p className="text-[20px] font-bold">Contact Information</p>
        <p>Help us complete your school profile</p>
        </div>
        <div className="w-[90%] space-y-3">
            {forms.map((form) => (
            <div className="flex flex-col w-[100%] ">
                <label htmlFor={form.name}>{form.label}</label>
                <input type={form.type} name={form.name} value={data.schoolName} onChange={(e) => changeData(e)} className="border-[1px] border-[#641BC4] h-[45px] w-[100%]"/>
                <p className="text-[12px]">{form.subtext}</p>
            </div>
        ))}
        <div className=" w-[100%] mb-2 ">
            <input type="radio" name="agreement" value={data.agreement} onChange={(e) => changeData(e)} className="mr-2"/>
                <label htmlFor="agreement">I agree to the ParaLearn RMS Terms of Service and Privacy Policy. I confirm that I have the authority to register this school.</label>
            </div>
        {/* submit button */}
        </div>
            {step == 3 &&   <div className="w-[100%] flex justify-evenly">
                   <button onClick={() => {setStep(step - 1)}} className="w-[35%] rounded-[12px]  font-semibold text-black h-[52px] flex flex-row items-center justify-center border-[1px] border-black">
            back </button>
            {/* create school */}
                <button onClick={() => {}} className="w-[35%] rounded-[12px] bg-[#641BC4] font-semibold text-white h-[52px] flex flex-row items-center justify-center">
            Create School </button>
                </div>}
    </div>
}